apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-processor
  namespace: ai-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-processor
  template:
    metadata:
      labels:
        app: ai-processor
    spec:
      containers:
        - name: ai-processor
          image: us-central1-docker.pkg.dev/dev-ops-475910/danushka-ar/ai-processor:latest
          imagePullPolicy: Always
          env:
        - name: GROQ_API_KEY
          value: "__GROQ_API_KEY_PLACEHOLDER__"
          ports:
            - containerPort: 8090

          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ai-processor
  namespace: ai-task
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: ai-processor
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
