apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-frontend
  namespace: ai-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-frontend
  template:
    metadata:
      labels:
        app: ai-frontend
    spec:
      containers:
        - name: ai-frontend
          image: LOCATION-docker.pkg.dev/PROJECT_ID/ai-task-repo/ai-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend
  namespace: ai-task
spec:
  selector:
    app: ai-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
